####READ ME

# Camera Calibration Using OpenCV

**This repository contains the code for [Camera Calibration Using Opencv](https://learnopencv.com/camera-calibration-using-opencv/) blog post**.

[<img src="https://learnopencv.com/wp-content/uploads/2022/07/download-button-e1657285155454.png" alt="download" width="200">](https://www.dropbox.com/sh/wp7kxnlptpg4o0l/AAC1Jp04cAuTitp3R6ustluMa?dl=1)

Calibrate your camera using OpenCV.

## Using the C++ code
### Compilation
To compile the `cameraCalibration.cpp`  and `cameraCalibrationWithUndistortion.cpp` code files, use the following:
```shell
mkdir build
cd build
cmake ..
cmake --build . --config Release
```
## Usage

### Using the C++ code

Refer to the following to use the compiled files:

```shell
./build/cameraCalibration
./build/cameraCalibrationWithUndistortion
```

### Using the python code

Refer to the following to use the `cameraCalibration.py` and `cameraCalibrationWithUndistortion.py` files respectively:

```shell
python3 cameraCalibration.py
python3 cameraCalibrationWithUndistortion.py
```

# AI Courses by OpenCV

Want to become an expert in AI? [AI Courses by OpenCV](https://opencv.org/courses/) is a great place to start. 

<a href="https://opencv.org/courses/">
<p align="center"> 
<img src="https://learnopencv.com/wp-content/uploads/2023/01/AI-Courses-By-OpenCV-Github.png">
</p>
</a>

In [1]:
#!/usr/bin/env python

import cv2
import numpy as np
import os
import glob

# Defining the dimensions of checkerboard
CHECKERBOARD = (6,9)
criteria = (cv2.TERM_CRITERIA_EPS + cv2.TERM_CRITERIA_MAX_ITER, 30, 0.001)

# Creating vector to store vectors of 3D points for each checkerboard image
objpoints = []
# Creating vector to store vectors of 2D points for each checkerboard image
imgpoints = [] 


# Defining the world coordinates for 3D points
objp = np.zeros((1, CHECKERBOARD[0]*CHECKERBOARD[1], 3), np.float32)
objp[0,:,:2] = np.mgrid[0:CHECKERBOARD[0], 0:CHECKERBOARD[1]].T.reshape(-1, 2)
prev_img_shape = None

# Extracting path of individual image stored in a given directory
images = glob.glob('./images/*.jpg')
for fname in images:
    img = cv2.imread(fname)
    gray = cv2.cvtColor(img,cv2.COLOR_BGR2GRAY)
    # Find the chess board corners
    # If desired number of corners are found in the image then ret = true
    ret, corners = cv2.findChessboardCorners(gray, CHECKERBOARD, cv2.CALIB_CB_ADAPTIVE_THRESH+
    	cv2.CALIB_CB_FAST_CHECK+cv2.CALIB_CB_NORMALIZE_IMAGE)
    
    """
    If desired number of corner are detected,
    we refine the pixel coordinates and display 
    them on the images of checker board
    """
    if ret == True:
        objpoints.append(objp)
        # refining pixel coordinates for given 2d points.
        corners2 = cv2.cornerSubPix(gray,corners,(11,11),(-1,-1),criteria)
        
        imgpoints.append(corners2)

        # Draw and display the corners
        img = cv2.drawChessboardCorners(img, CHECKERBOARD, corners2,ret)
    
    cv2.imshow('img',img)
    cv2.waitKey(0)

cv2.destroyAllWindows()

h,w = img.shape[:2]

"""
Performing camera calibration by 
passing the value of known 3D points (objpoints)
and corresponding pixel coordinates of the 
detected corners (imgpoints)
"""
ret, mtx, dist, rvecs, tvecs = cv2.calibrateCamera(objpoints, imgpoints, gray.shape[::-1],None,None)

print("Camera matrix : \n")
print(mtx)
print("dist : \n")
print(dist)
print("rvecs : \n")
print(rvecs)
print("tvecs : \n")
print(tvecs)

Camera matrix : 

[[503.68477278   0.         313.67563674]
 [  0.         503.37989194 243.25575476]
 [  0.           0.           1.        ]]
dist : 

[[ 2.08346324e-01 -4.68650266e-01  4.51079181e-04 -1.93373893e-03
   2.37592401e-01]]
rvecs : 

(array([[-0.31060359],
       [ 0.1515558 ],
       [ 1.57720394]]), array([[0.3139181 ],
       [0.58736866],
       [1.39910762]]), array([[0.33307297],
       [0.55841704],
       [1.39532836]]), array([[0.78743976],
       [0.53294469],
       [1.52233962]]), array([[0.42519317],
       [0.68127945],
       [1.34442524]]), array([[-0.40676505],
       [-0.72194813],
       [ 1.36334531]]), array([[-0.41607396],
       [-0.7647259 ],
       [ 1.33850247]]), array([[-0.23343341],
       [-0.04621596],
       [ 1.522275  ]]), array([[ 0.11068043],
       [-0.46502899],
       [ 1.48272651]]), array([[0.84715318],
       [0.19610195],
       [1.46485457]]), array([[0.28284572],
       [0.58780705],
       [1.3194868 ]]), array([[0.15172276]